[project]
name = "iceberg-demos"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "parquet-cli>=1.3",
    "parquet-tools>=0.2.16",
    "polars>=1.36.1",
    "pyiceberg[pyarrow,sql-sqlite]>=0.10.0",
]
